### ISSUE TITLE
首页图片显示问题

### ISSUE THREAD

**Issue by yehongwei** [xujeff/tianti#13]
如何显示首页的图片？
![default](https://user-images.githubusercontent.com/22806337/31869823-1558c1ac-b7dd-11e7-8478-9c3c9f7dfd67.png)

**Comment by ouyangning** [comment]
我也遇到了和你一样的问题，你有解决方案了吗？

**Comment by ouyangning** [comment]
图片并不在GitHub的源代码里，需要自己从重新后台上传。
